// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PesquisasStartup.Infraestrutura.Context;

#nullable disable

namespace PesquisasStartup.Infraestrutura.Migrations
{
    [DbContext(typeof(PesquisasStartupContext))]
    [Migration("20251219215853_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PesquisasStartup.Dominio.Entidades.Pesquisas.Pesquisa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pesquisas");
                });

            modelBuilder.Entity("PesquisasStartup.Dominio.Entidades.Pesquisas.Pesquisa", b =>
                {
                    b.OwnsMany("PesquisasStartup.Dominio.Entidades.Pesquisas.Pergunta", "Perguntas", b1 =>
                        {
                            b1.Property<Guid>("PesquisaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Enunciado")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PesquisaId", "Id");

                            b1.ToTable("Pergunta");

                            b1.WithOwner()
                                .HasForeignKey("PesquisaId");

                            b1.OwnsMany("PesquisasStartup.Dominio.Entidades.Pesquisas.Alternativa", "Alternativas", b2 =>
                                {
                                    b2.Property<Guid>("PerguntaPesquisaId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("PerguntaId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Opcao")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(1)");

                                    b2.Property<string>("Texto")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PerguntaPesquisaId", "PerguntaId", "Id");

                                    b2.ToTable("Alternativa");

                                    b2.WithOwner()
                                        .HasForeignKey("PerguntaPesquisaId", "PerguntaId");
                                });

                            b1.Navigation("Alternativas");
                        });

                    b.OwnsMany("PesquisasStartup.Dominio.Entidades.Pesquisas.Resposta", "Respostas", b1 =>
                        {
                            b1.Property<Guid>("PesquisaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Alternativa")
                                .IsRequired()
                                .HasColumnType("nvarchar(1)");

                            b1.Property<DateTime>("Data")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Pergunta")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PesquisaId", "Id");

                            b1.ToTable("Resposta");

                            b1.WithOwner()
                                .HasForeignKey("PesquisaId");

                            b1.OwnsOne("PesquisasStartup.Dominio.Entidades.Pesquisas.Cpf", "CpfPessoa", b2 =>
                                {
                                    b2.Property<Guid>("RespostaPesquisaId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("RespostaId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("RespostaPesquisaId", "RespostaId");

                                    b2.ToTable("Resposta");

                                    b2.WithOwner()
                                        .HasForeignKey("RespostaPesquisaId", "RespostaId");
                                });

                            b1.Navigation("CpfPessoa")
                                .IsRequired();
                        });

                    b.OwnsMany("PesquisasStartup.Dominio.Entidades.Pesquisas.SituacaoPesquisa", "Situacoes", b1 =>
                        {
                            b1.Property<Guid>("PesquisaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("DataHora")
                                .HasColumnType("datetime2");

                            b1.Property<int>("TipoSituacao")
                                .HasColumnType("int");

                            b1.HasKey("PesquisaId", "Id");

                            b1.ToTable("SituacaoPesquisa");

                            b1.WithOwner()
                                .HasForeignKey("PesquisaId");
                        });

                    b.Navigation("Perguntas");

                    b.Navigation("Respostas");

                    b.Navigation("Situacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
